// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zmk-glazing/CurrentGlazing.tsx": () => import("../components/mockups/zmk-glazing/CurrentGlazing.tsx"),
  "./components/mockups/zmk-glazing/UpdatedGlazing.tsx": () => import("../components/mockups/zmk-glazing/UpdatedGlazing.tsx"),
  "./components/mockups/zmk-header-contacts/CurrentHeaderContact.tsx": () => import("../components/mockups/zmk-header-contacts/CurrentHeaderContact.tsx"),
  "./components/mockups/zmk-header-contacts/HeaderContactActions.tsx": () => import("../components/mockups/zmk-header-contacts/HeaderContactActions.tsx"),
  "./components/mockups/zmk-3d/SandwichPanel3D.tsx": () => import("../components/mockups/zmk-3d/SandwichPanel3D.tsx"),
  "./components/mockups/zmk-3d/WarehouseFrame3D.tsx": () => import("../components/mockups/zmk-3d/WarehouseFrame3D.tsx")
};
